language: cpp

matrix:
  include:
    - os: osx

install:
  - brew update
  - brew install qt5
  - brew link --force qt5

script:
  - qmake 3DSTimeFinder.pro
  - make -j $(sysctl -n hw.physicalcpu)

before_deploy:
  - /usr/local/Cellar/qt/5.13.2/bin/macdeployqt 3DSTimeFinder.app -dmg -verbose=2
  - zip -r 3DSTimeFinder-macOS.zip 3DSTimeFinder.dmg
  - shasum -a 256 3DSTimeFinder-macOS.zip > 3DSTimeFinder-macOS.zip.sha256


deploy:
  provider: releases
  api_key:
    secure: HXoTmPvwpCRpVcS/fddHHQVvoaw/cELTPFLG2Q7G98MTX6wgxIWG9mmJEybZRHjwpgWgGwW1UgZKXUyoyrKiBrlppkczl5VE7xY7GzdU2mIBpN7u72YuS2KExnthZGScsty8Jyt2ZoSHV3RHBV8aINiC2fwyH9k5OW3wQ4MFRww18YluFUmO/bOMTG83V6hv4YkpN9nf9D+eduoetJdaMftHPNrvxE87CwhP+QIhoKc+s3jCW9a+6T3Zyu09S4ox7zjnxYgkvlAK2eFedfTGNeLspem8PPh/4mx54MVEOgKgl6l/QWYU4yD/NBdshlR+kLnsyKARZx67/h50arYFHpmLcdnxNfHJSo0AT9n+zai2AI0mXCym9qnkCfmPX+GC3wpNOcJapEunSZvvb1zbG8FgkptWB8MHZts8rStGKj7Eeagh7hJ4hxNuuPD4f8oHEEjweJx08JYym6/UQzLHjn0pvkHvst0E3J99r7dmbgoL/eTRTMKv0MxjPHL7w02lD/peHRiuFjI+Dn0BX3ZbeDKanK+PkLoZ4E0vVC50stETF+zRiQYhS3c00TYW/cklCe+loBOqcb08wD5vuD9qw0MH4+7OaqHBxFBP5oWyEANtjtvs9n058aAMm7SrySmolZIZSWGfSAF4V97/HCCBhShXs/SnKUiPn8e2+zgk7Iw=
  file: 
    - "3DSTimeFinder-macOS.zip"
    - "3DSTimeFinder-macOS.zip.sha256"
  skip_cleanup: true
  on:
    repo: Admiral-Fish/3DSTimeFinder
    tags: true
